// Module2_FrontendDev/Velu Rahul L/handson_05/student-portal-react/src/components/CourseCard.jsx
function CourseCard({

name,
code,
credits,
grade,
onEnroll

}){

return(

<div
className="course-card"
style={{
background:"white",
padding:"20px",
borderRadius:"10px",
boxShadow:"0 0 8px rgba(0,0,0,.2)"
}}
>

<h3>{name}</h3>

<p>
<strong>Course Code :</strong> {code}
</p>

<p>
<strong>Credits :</strong> {credits}
</p>

<p>
<strong>Grade :</strong> {grade}
</p>

<button

style={{
marginTop:"10px",
padding:"10px 15px",
background:"#1565c0",
color:"white",
border:"none",
cursor:"pointer",
borderRadius:"5px"
}}

onClick={onEnroll}

>

Enroll

</button>

</div>

);

}

export default CourseCard;

// Module2_FrontendDev/Velu Rahul L/handson_08/student-portal-vue/src/components/CourseCard.vue
<template>

<div class="card">

<h2>{{ name }}</h2>

<p>

Course Code : {{ code }}

</p>

<p>

Credits : {{ credits }}

</p>

<p>

Grade : {{ grade }}

</p>

<button @click="enroll">

Enroll

</button>

</div>

</template>

<script setup>

const props = defineProps({

name:String,

code:String,

credits:Number,

grade:String

});

function enroll(){

alert(props.name+" Enrolled Successfully");

}

</script>

<style scoped>

.card{

border:1px solid #ddd;

padding:20px;

margin:15px;

border-radius:10px;

box-shadow:0 0 8px rgba(0,0,0,.2);

}

button{

margin-top:15px;

padding:10px 18px;

background:#1565c0;

color:white;

border:none;

cursor:pointer;

border-radius:5px;

}

</style>
