// Module2_FrontendDev/Velu Rahul L/handson_08/student-portal-vue/src/components/Header.vue
<template>

<header>

<h2>

Student Portal

</h2>

<nav>

<RouterLink to="/">

Home

</RouterLink>

<RouterLink to="/courses">

Courses

</RouterLink>

<RouterLink to="/profile">

Profile

</RouterLink>

</nav>

</header>

</template>

<script setup>

import {

RouterLink

}

from "vue-router";

</script>

<style scoped>

header{

display:flex;

justify-content:space-between;

align-items:center;

padding:20px;

background:#1565c0;

}

h2{

color:white;

}

nav{

display:flex;

gap:20px;

}

a{

color:white;

text-decoration:none;

font-weight:bold;

}

</style>

// Module2_FrontendDev/Velu Rahul L/handson_05/student-portal-react/src/components/Header.jsx
function Header({ siteName, count }) {

    return (

        <header
            style={{
                background: "#1565c0",
                color: "white",
                padding: "20px",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center"
            }}
        >

            <h2>{siteName}</h2>

            <nav>

                <a href="#" style={{ color: "white", marginRight: "20px" }}>Home</a>

                <a href="#" style={{ color: "white", marginRight: "20px" }}>Courses</a>

                <a href="#" style={{ color: "white", marginRight: "20px" }}>Profile</a>

            </nav>

            <h4>Enrolled : {count}</h4>

        </header>

    );

}

export default Header;
