// Module2_FrontendDev/Velu Rahul L/handson_06/student-portal-react/src/components/Header.jsx
import { Link } from "react-router-dom";

import { useContext } from "react";

import { EnrollmentContext }

from "../context/EnrollmentContext";

function Header(){

const {

enrolledCourses

}

=

useContext(

EnrollmentContext

);

return(

<header>

<h2>

Student Portal

</h2>

<nav>

<Link to="/">Home</Link>

<Link to="/courses">Courses</Link>

<Link to="/profile">Profile</Link>

</nav>

<h3>

Enrolled :

{enrolledCourses.length}

</h3>

</header>

);

}

export default Header;

// Module2_FrontendDev/Velu Rahul L/handson_07/student-portal-angular/src/app/components/header/header.component.ts
import { Component } from '@angular/core';

@Component({

selector:'app-header',

templateUrl:'./header.component.html',

styleUrls:['./header.component.css']

})

export class HeaderComponent{

}

<header>

<h2>

Student Portal

</h2>

<nav>

<a routerLink="/">Home</a>

<a routerLink="/">Courses</a>

<a routerLink="/profile">

Profile

</a>

</nav>

</header>
